- package.json
On the last merge of #17 we forgot to release a beta. Updating so the build on travis for ``metadata-sync`` works properly.
> [Fix] Bump beta version

- package.json
- src/api/d2-api.ts
- src/api/system.ts
Closes #37 
Published: https://www.npmjs.com/package/d2-api/v/0.2.2-beta.1
I have implemented all `/api/system` endpoints except for `taskSummaries`, as it always returns `null` (tested in different dhis2 versions in play, also dev). I'd need to debug dhis2-core to be sure what the problem is, and open a JIRA issue if necessary. Since we don't use that endpoint (for now), I've done no further research.
OK: https://play.dhis2.org/2.32.4/api/system/tasks/DATA_SET_NOTIFICATION
Fail: https://play.dhis2.org/2.32.4/api/system/taskSummaries/DATA_SET_NOTIFICATION
> Implement /api/system endpoints

- README.md
- package.json
- src/api/d2Api.ts
- src/api/types.ts
- src/data/AxiosHttpClientRepository.ts
- src/data/FetchHttpClientRepository.ts
- src/repositories/HttpClientRepository.ts
Required by https://github.com/EyeSeeTea/project-monitoring-app/pull/338
Implementation:
- The option `timeout` can be passed both on the `D2Api` instantiation (it will be used by default) or overriden in a particular API request 
- XHR: Axios already has a `timeout` option, so just forward it.
- Fetch: The Fetch API does not implement an inbuilt timeout mechanism, so we use `setTimeout` + `controller.abort`.
> Implement timeout

- package.json
- src/data/FetchHttpClientRepository.ts
This solves the issue with special characters such as "Côte d'Ivoire". However we still have problems storing in the dataStore the inverted apostrophe, to fix them we should be able to either set as an option the charset (which I dislike) or magically detect it from contents before doing POST/PUT operations.
Alternatively I believe we should be good if we ask "WIDP IT Team" to clean-up from the database in NHWA modules the incorrect apostrophes appears 3 times. The character (special aprostrophe "’") and use normal apostrophes instead.
> [Fix] Handle different encodings with fetch

- package.json
- src/data/FetchHttpClientRepository.ts
- yarn.lock
- Browser and NodeJS have different implementations of ``TextDecoder``
- DHIS2 uses ``latin1`` in some endpoints (such as dataStore)
- NodeJS implementation does not have ``latin1`` support
- Switch from ``TextDecoder`` to ``iconv-lite``
> [Fix] Change TextDecoder to iconv-lite

- package.json
- src/api/common.ts
- src/api/inference.ts
Required by https://github.com/EyeSeeTea/project-monitoring-app/issues/333
https://docs.dhis2.org/2.30/en/developer/html/dhis2_developer_manual_full.html#webapi_field_transformers
Note: transformers may be chainable (`organisationUnits~size~rename(ou)`), so we don't really capture the full specs. For some other issue.
> Implement field transformer ~size

- package.json
- src/2.32/schemas.ts
- src/2.33/schemas.ts
- src/2.34/index.ts
- src/2.34/schemas.ts
- src/schemas/base.ts
- src/scripts/generate-schemas.ts
Currently, not required by any project. I had the idea to use it in metadata-sync transformations, but currently we use no typing there, it only makes sense when fully typed.
Also: it orders schemas by name, on each generation the order was random and source diffs were useless.
> Add support for version 2.34 [NOT FOR 1.1.0]

- package.json
- src/api/dataStore.ts
Required by https://app.clickup.com/t/gz1b56
Problem: When the session is lost, DHIS2 does a 302-redirect + 200-html containing the login page (!). This is wrong and dangerous if our particular operation did not check the response, only the status code.
This PR addresses partially the problem:
- For dataStore, check POST/PUT/DELETE return value. We'll need to discuss how to tackle the rest of the problem, there are many ways to do it (and some may break existing code).
> [data store] validate response of update operations

- package.json
- src/api/d2Api.ts
- src/api/dataStore.ts
- src/api/maintenance.ts
- src/api/system.ts
- src/data/AxiosHttpClientRepository.ts
Required by https://github.com/EyeSeeTea/project-monitoring-app/pull/389
The task only needed categoryOptionComboUpdate, but I added all of them anyway for future usage.
See https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/maintenance.html
> Add endpoint maintenance

- package.json
- src/api/dataValues.ts
Tasks:
1) Implement POST /api/dataValues for a single data value. Using `data: new URLSearchParams(...)`  + `dataType: "raw"` to build the form data.
2) AFICS, it's not documented, but data values have a boolean `deleted` property, as the source code reveals:
https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-api/src/main/java/org/hisp/dhis/datavalue/DataValue.java#L100
This property must be used in conjunction with `updateStrategy=DELETE` to be able to delete values using `/dataValueSets`.
> [data-values] post single value + add deleted <property>

- package.json
- src/api/audit.ts
- src/api/d2Api.ts
Adds paginated endpoint `audit/dataValues`. We dismissed having conditional types to avoid complexity for paging yes/no, so we have to decide if we duplicate the endpoints or not.
> [data value] audits

- src/api/events.ts
Required by https://app.clickup.com/t/1hkf28g
Still some missing, but not sure the docs are exact though (for example `eventIdScheme` does not appear in the docs, but it does exist):
https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-235/web-api.html#webapi_import_parameters
> [events] typed status + strategy import param

- package.json
- src/api/dataStore.ts
- src/api/system.ts
- src/data/AxiosHttpClientRepository.ts
- src/data/FetchHttpClientRepository.ts
- src/repositories/CancelableResponse.ts
Closes https://app.clickup.com/t/1u62crd
Use deferrable responses so promises run only on `res.getData()`
Implementation:
- Fix any scenario where the promise should not effectively execute until required (i.e. when using future wrappers).
- Instead of working with `promiseResponse`, work with `() => promiseResponse`. 
NOTES:
- Beta release: https://www.npmjs.com/package/@eyeseetea/d2-api/v/1.10.1-beta.1
- It should not be a breaking change, but make sure that your app is working properly when updating. 
- Being used in `data-management` and `central-planning-reporting.`
> Return lazy promises

- package.json
- src/api/trackedEntityInstances.ts
- src/schemas/base.ts
- src/scripts/generate-schemas.ts
Required by https://app.clickup.com/t/1vqyygd
- Added some missing fields to TEI type.
- Add geometry fields to TEI type.
- Create specific type `TrackedEntityInstanceToPost`
- Fix `D2Geometry` polygon type
- Support `D2ProgramOwner` custom type.
- Set v2.34 as deprecated.
(schemas not updated, some play.dhis2 servers are down)
> Extend tracked entity instances types (geometry + specific post type)

- src/api/d2Api.ts
In all current apps I believe we have already switched to ``fetch`` backend. Make it default and probably deprecated in next major?
Related: https://github.com/nodejs/node/pull/41749. Node will soon have a ``fetch`` compliant implementation on top of ``undici`` exposed as a Global.
> [Feature] Change default backend to fetch

- .eslintrc.js
- package.json
- src/2.35/schemas.ts
- src/2.36/schemas.ts
- src/2.37/schemas.ts
- src/api/common.ts
- src/api/events.ts
- src/index.ts
- src/schemas/base.ts
- src/scripts/generate-schemas.ts
Required by: https://app.clickup.com/t/1yyx3m4
May benefit: https://app.clickup.com/t/1yt6b2e
Implementation:
- v2.36 changed the fields that the events endpoint returned by default, which breaks apps. Since the endpoint now has full support for schema-able `fields`, we've made it compulsory (like we do when querying metadata or model objects) so apps will be forced to pass which specific `fields` are needed. 
- On the same line, apps will be probably using `Event` from the API, but now that's the global type and the specific type will depend on the fields. Good thing is that TS will force the dev to refactor it.
- Type `Event` has been renamed to `D2Event`. Reasons: 1) align with all other interface names from the API. 2) `Event` is a global interface name, it's bad practice to clobber …
> [events] Fix/refactor endpoint for 2.36

- package.json
- src/2.35/schemas.ts
- src/2.36/schemas.ts
- src/2.37/schemas.ts
- src/schemas/base.ts
- src/scripts/generate-schemas.ts
Required by https://app.clickup.com/t/2amhvhn
Currently, the property "access" did not contain "data", but `dataShareable`-models do have this property: add dynamically depending on the schema.
> Add data property to access if schema is dataShareable

- package.json
- src/api/common.ts
- src/api/d2Api.ts
- src/api/dataStore.ts
- src/api/events.ts
Required by https://app.clickup.com/t/29qy7bq
Notes:
- `/api/events` supports a custom `filter` param, see https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/tracker.html#webapi_events (not specifically documented for events)
- A 409 is considered a valid response, the caller can then inspect the response.
- Add WARNING as a possible status value for importSummaries.
> Refine events endpoint (status values, 409 control, filter field)

- src/api/tracker.ts
- src/api/trackerEnrollments.ts
- src/api/trackerEvents.ts
- src/api/trackerTrackedEntities.ts
Related task: [Implement d2-api usage for EGASP (so it uses the new tracker endpoint)](https://app.clickup.com/t/865cua9zv)
Consuming code:
- `/tracker/events` -> https://github.com/EyeSeeTea/glass-dev/pull/176/files#diff-24915276d1e44c612c0e09d97ff50433136ee8d977768353f5f2a6c6a9eea181
- `/tracker/trackedEntities` ->  https://github.com/EyeSeeTea/glass-dev/pull/176/files#diff-e085a45593ebd7b2ceff539ece77a1afd0c1b37160a3624cb1f75a6975d5be5cL108
> New tracker endpoints: /events & /trackedEntities

- src/api/files.ts
Related task: [Implement documents deletion in d2-api and include it when deleting files in GLASS](https://app.clickup.com/t/860q9r9yx)
Consuming code:
/documents/<document-id> -> https://github.com/EyeSeeTea/glass-dev/pull/178/commits/3f13067d2160365b6ff7c75646dd933687acfb9b
> DELETE document endpoint

- package.json
- src/api/events.ts
- src/api/trackedEntityInstances.ts
This is a type-only improvement:
- Fix usage of `Event` in `Enrollment` type (was using the global DOM Event, not `D2Event`)
- Create `TrackedEntityInstanceToPost`.
> [tracker] Fix Enrollment.events type + create TEI-to-post type

- package.json
- scripts/publish.sh
- src/api/files.ts
- yarn.lock
Required by https://app.clickup.com/t/865cqypkn
Implementation:
- Blob is not support for Node. Solution: allow to pass a `Buffer`.
- Class `FormData` is not implemented in Node. Solution: Add a wrapper package (form-data)
> [api.files] Add support for NodeJs

- src/api/trackerEvents.ts
According with the [documentation of the new Tracker API](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/tracker.html#events) :
- Change tracker event status `SCHEDULED` to `SCHEDULE`
Error creating an event with SCHEDULED status:
Correct status:
> Change tracker event status from SCHEDULED to SCHEDULE

- package.json
- src/api/trackerEnrollments.ts
- src/api/trackerEvents.ts
- src/api/trackerTrackedEntities.ts
-   **Issue:** Closes
- Fix D2TrackedEntityInstanceToPost type omitting enrollments type instead of events
> Fix D2TrackedEntityInstanceToPost type

- src/data/AxiosHttpClientRepository.ts
- src/data/FetchHttpClientRepository.ts
Detected on https://app.clickup.com/t/8697ycwm0 
When an HTTP error occurs and is logged using `console.error` in a Node.js environment, the thrown error is an object, which may result in incomplete output.
> [feature] Add extra console.logs on catch branch

- README.md
- package.json
- scripts/publish.sh
- src/api/common.ts
- src/api/trackerEnrollments.ts
- src/api/trackerEvents.ts
- src/api/trackerTrackedEntities.ts
-   **Issue:** Closes https://app.clickup.com/t/86964a9ua
- In v41 the tracker endpoints `/tracker/trackedEntities`, `/tracker/events` and `/tracker/enrollments` no longer returns the data in an `instances` array anymore. Now they are using a key named after the plural of the returned entity.
`/tracker/trackedEntities`
```json
{
"trackedEntities": [...]
}
```
`/tracker/events`
```json
{
"events": [...]
}
```
`/tracker/enrollments`
```json
{
"enrollments": [...]
}
```
In order to keep backwards compatibility and to avoid breaking changes in `d2-api` we'll keep the `instances` attribute checking for an `instances` array and if there's none we fall back to `trackedEntities`, `events` or `enrollments` according to the requested endpoint.
- Also now the pagination information is included in a …
> add support for tracker v41

- package.json
- src/api/tracker.ts
- src/api/trackerEnrollments.ts
- src/api/trackerEvents.ts
- src/api/trackerTrackedEntities.ts
- src/data/AxiosHttpClientRepository.ts
Required by https://github.com/EyeSeeTea/d2-tools/pull/59
> [fix] Support all fields keyword

- package.json
- scripts/publish.sh
> Clean folder before build

- src/repositories/HttpClientRepository.ts
The DHIS2 Web API add supports PATCH Method for partial updates using the JSON Patch format. 
https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/metadata.html#webapi_partial_updates
I use it to edit disable user field.
[
{ "op": "replace", "path": "/disabled", "value": true }
]
to the endpoint /api/41/users/USER_ID using a PATCH request. Your d2-api usage is correct, but since  ttpClientRepository.d.ts lacked "patch" in its Method type, adding it manually like you did is fine. 
I need to set the Content-Type header to application/json-patch+json. 
Maybe that could be implemented in the d2-api in some way but I used this:
await this.api
.request<string>({
method: "patch",
url: `/41/users/${userId}`,
headers: { "Content-Type": "application/json-patch+json" },
data: [{ op: …
> [feature] Add PATCH method to manual API requests

- src/api/files.ts
- src/data/FetchHttpClientRepository.ts
https://app.clickup.com/t/8699x5zxj
Problem:
[backend: fetch]
After updating d2-tools to Node v18, file uploads with fetch using multipart form data stopped working (response from DHIS2: `org.springframework.web.multipart.MultipartException: Current request is not a multipart request`).
This was unexpected, as Node 18 added native support for fetch. The issue is that this fetch implementation does not handle FormData the same way browsers do.
Solution:
Tested:
Notes:
There exists https://www.npmjs.com/package/formdata-node, which should, in principle, fix the problems with native Node fetch and FileData. However, it's a Node-only module, so we cannot directly use it. In principle, it should be possible with some manual imports, but as the cross-fetch solution is simple enough, I think the …
> [feature] Support fetch+FormData for node 18 [backend: fetch]

- README.md
- src/api/common.ts
- src/api/d2Api.ts
- src/api/model.ts
- src/api/patch.ts
- src/repositories/HttpClientRepository.ts
-   **Issue:** #8699r8t7c Closes [Change User-Extended App user group API mechanism](https://app.clickup.com/t/8699r8t7c)
- **OLD** DHIS2 Documentation: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-241/metadata.html?h=develop#webapi_collections_adding_removing_objects_single_request
- **NEW** DHIS2 Documentation: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-241/metadata.html?h=develop#webapi_partial_updates
The patch method supports the following operations according to [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902) and DHIS2 extensions. The `path` field uses [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) syntax:
-   **`add`**: Adds a value to an object or array
-   **`remove`**: Removes a value from an object or array
- …
> Add PATCH request method to D2ApiGeneric and to Model
