package.json, src/api/common.ts, src/index.ts, src/react/context.ts, src/react/useD2ApiData.ts, yarn.lock
- Add dependencies and update build rules to allow ``babel --watch``
- Add ``context`` from ``project-monitoring-app``
- Instead of creating a default ``localhost`` context, throw if not implemented
- Add ``useD2ApiData`` hook for react querying
=> Basic react support

package.json, src/api/common.ts, src/api/d2-api.ts, src/api/metadata.ts, src/api/models.ts, src/index.ts
Required by https://github.com/EyeSeeTea/project-monitoring-app/pull/75
=> Narrow types for models.PUT/POST and metadata.POST

README.md, package.json, src/api/analytics.ts, src/api/d2-api.ts, src/index.ts
Required by https://github.com/EyeSeeTea/project-monitoring-app/pull/95
- analytics GET (see README)
=> Endpoint analytics

src/react/useD2ApiData.ts
=> Fix problem of calling getData without binding context

package.json, src/api/dataStore.ts
Required by project-monitoring-app/pull/168
=> Implement dataStore.delete

package.json, src/api/dataStore.ts
Required by metadata-synchronization/pull/472
=> Implement namespace.getKeys()

package.json, src/2.30/index.ts, src/2.30/schemas.ts, src/2.31/index.ts, src/2.31/schemas.ts, src/2.32/schemas.ts, src/2.33/index.ts, src/api/d2Api.ts, src/schemas/base.ts, src/scripts/generate-schemas.ts
This reverts commit c1725058d86ddcccd80c8e380e7cadbba6a0aa19.
=> Revert "Enable schemas for nested properties"

package.json, src/api/appHub.ts, src/api/d2Api.ts
- https://app.clickup.com/t/d31beu
=> [Feature] Add app hub endpoint

package.json, src/api/common.ts, src/api/d2Api.ts, src/api/dataStore.ts, src/api/dataValues.ts, src/api/events.ts, src/api/metadata.ts, src/api/sharing.ts, src/api/system.ts, src/utils/promises.ts, src/utils/types.ts
Pending:
- get/getAll split on models too
=> [Feature] Add methods for async task

package.json, src/api/system.ts
Use ``_.some`` instead of ``[0]`` to be more robust in case the array is not sorted by most recent
=> [Fix] Async task check

package.json, src/schemas/base.ts
Add missing type for this scenario:
=> Add missing type in D2RelationshipConstraint union

package.json, src/api/files.ts, src/data/FetchHttpClientRepository.ts
- https://app.clickup.com/t/j9apnt
Published as ``1.8.6-beta.1``
Required on MDSync for ``documents sync`` feature
=> [Feature] Add get document by id method

package.json, src/api/d2Api.ts, src/api/expressions.ts, src/api/files.ts, src/data/FetchHttpClientRepository.ts, src/repositories/HttpClientRepository.ts
- Add a new expression endpoint utility to ``d2-api``
- Used in ``predictors-extended`` app
=> [Feature] Add expression description endpoint

package.json, src/api/dataValues.ts
We need bodyType to raw for POST /dataValue
=> Fix data values to send dataType

package.json, src/api/dataValues.ts, src/api/expressions.ts, src/api/files.ts, src/data/FetchHttpClientRepository.ts, src/repositories/HttpClientRepository.ts
- Rename dataType to more meaningful name
- Bump beta
=> [Fix] Documents upload data type

src/api/UserLookup.ts, src/api/d2Api.ts
Required by https://app.clickup.com/t/1gbfz66
Implements /api/userLookup (get by id + query)
https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-236/users.html#user-lookup
=> Implement endpoint /api/userLookup

src/api/system.ts
-   **Issue:** Closes https://app.clickup.com/t/865cpwt3a
Details about this change here: https://github.com/EyeSeeTea/d2-tools/pull/35
=> adding server timezone type

src/api/trackerEnrollments.ts, src/api/trackerEvents.ts, src/api/trackerTrackedEntities.ts
The prop was missing from the types.
Related: https://github.com/EyeSeeTea/d2-api/pull/141
=> Add skipPaging option to new tracker endpoints

package.json, src/api/trackerTrackedEntities.ts
task : https://app.clickup.com/t/8694tp2rg
Implementation : Adding code property to Attribute.
=> fix: add code to tracker entity attribute

README.md, package.json, src/api/analytics.ts, src/utils/types.ts
Following [Zebra program indicator feature](https://app.clickup.com/t/8694tp0tp) we needed to get enrollments query in analytics `/analytics/enrollments/query/`
- New method `analytics.getEnrollmentsQuery`
#8694tp0tp
=> Feature: Add `analytics.getEnrollmentsQuery` method

package.json, src/api/events.ts, src/api/trackerTrackedEntities.ts
Required by https://github.com/EyeSeeTea/central-planning-reporting/pull/383
This PR fixes some typos
=> [fix] property names

src/api/trackerEnrollments.ts, src/api/trackerEvents.ts, src/api/trackerTrackedEntities.ts
-   **Issue:** https://app.clickup.com/t/8697kr6qt
- Change required fields to post using new api tracker for events, trackedEntities and enrollments 
- Documentation: [migration guide from v2.38](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-238/new-tracker.html#changes-in-the-api) and [v2.41 tracker](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-241/tracker.html#webapi_nti_tracker_objects)  (in other versions is the same)
- Remember first create the enrollment and get uid from response inside `bundleReport.typeReportMap.ENROLLMENT.objectReports` to set `trackedEntity` when creating the trackedEntity
**EVENT:**
```shell
curl --location 'https://play.im.dhis2.org/stable-2-41-3/api/tracker?async=false' --header "Content-Type: application/json" …
```
=> Change required fields to post using new api tracker

package.json, src/data/FetchHttpClientRepository.ts
* **Issue:** Closes #869amwuzv https://app.clickup.com/t/869amwuzv
- handle undefined agent
=> fix: handle undefined agent in getAgentOptions
